# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/db/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { except_tables = ["field_logs"] } # Don't create a schema for the field_logs table, since it does not include a primary key.

[migrations_directory]
dir = "migrations"
